# Generated by Django 4.2.5 on 2023-10-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(help_text="Entre o nome", max_length=100),
                ),
                (
                    "idade",
                    models.IntegerField(
                        blank=True, help_text="Entre a idade", null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Informe o email", max_length=254, unique=True
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
