# Generated by Django 4.2.6 on 2023-11-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
