# Generated by Django 4.2.5 on 2023-10-27 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Digite o titulo do filme", max_length=50
                    ),
                ),
                (
                    "nacionalidade",
                    models.CharField(
                        help_text="Digite a nacionalidade do filme", max_length=50
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        help_text="Digite o ano de lancamento do filme", max_length=50
                    ),
                ),
                (
                    "sinopse",
                    models.CharField(
                        blank=True,
                        help_text="Digite o titulo do filme",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "diretor",
                    models.CharField(
                        help_text="Digite o nome do diretor", max_length=50
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        help_text="Digite a nota que avalia o filme",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "review",
                    models.CharField(
                        blank=True,
                        help_text="Digite um breve review do filme",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("visto", models.BooleanField(default=False)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
