# Generated by Django 4.2.6 on 2023-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filme',
            options={'managed': True, 'ordering': ['titulo']},
        ),
        migrations.RemoveField(
            model_name='filme',
            name='id',
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(help_text='Digite o titulo do filme', max_length=50, primary_key=True, serialize=False),
        ),
    ]
